### ISSUE TITLE
Allow aws-switchrole to work with multiple account structure (AWS Organizations)

### ISSUE THREAD

**Issue by hussfelt** [hybby/aws-switchrole#11] opened 2017-12-14 07:14 UTC
Hello!

First off; thanks for a great tool!

Where I am currently working we have a setup with multiple aws accounts under one root account. All our users have an IAM user in our root account and are then allowed to assume different roles in the sub-accounts using cross-account policies.

With this tool defaulting to using the actual profile when assuming the role (https://github.com/hybby/aws-switchrole/blob/master/aws-switchrole.py#L149) it will fail for all assumes that does not specifically target a role in the sub-account that has ```sts:assumeRole``` privilege.

At least that's what I think is happening :-)

Looking into fixing this by adding an option to use default credentials when assuming the role chosen.

Example config:

```
[default]
region = eu-west-1
output = json
[preview]
cloudfront = true

[profile dr-account3]
role_arn = arn:aws:iam::1234567899:role/Administrator
source_profile = default
region = eu-west-1

[profile dr-account2]
source_profile = dr-otherprofile
region = eu-west-1

[profile dr-account1]
role_arn = arn:aws:iam::123456789:role/Implementation
source_profile = default
region = eu-west-1
```

Default credentials:

```
[default]
aws_access_key_id = AKIASOMKEY
aws_secret_access_key = SOMESECRET
```

**Comment by hussfelt** [comment] 2017-12-14 07:46
I am seriously a bit unclear as to why this happens.

In my case the below command:

```
aws sts assume-role --role-arn arn:aws:iam:: 123456789:role/Implementation --role-session-name dr-notwork-141217074137 --profile dr-notwork
```

Gives this strange error

```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts:: 123456789:assumed-role/Implementation/botocore-session-1513236525 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam:: 123456789:role/Implementation
problem parsing AWS response. STDOUT and STDERR below:
STDOUT:

STDERR:
None
```

Running this, and not involving the profile works:

```
aws sts assume-role --role-arn arn:aws:iam:: 123456789:role/Implementation --role-session-name dr-notwork-141217074137
```

**Comment by hussfelt** [comment] 2017-12-14 07:55
It feels like a catch 22, using the profile and respecting ```source_profile``` argument but then not really using the credentials but some temporary ones. Almost like the bug itself actually resides within ```aws sts``` command.

**Comment by hybby** [comment] 2017-12-14 08:10
Hello @hussfelt, thanks for your PR!

It sounds like what’s happening here is that the role described by the ‘role_arn’ in your profile doesn’t have access to ‘sts:AssumeRole’

My understanding is that first the ‘role_arn’ in the profile is passed to your principal (your source AWS IAM user) and then the ‘sts:AssumeRole’ call is made.

So, your ‘role_arn’ Role should have a policy statement to allow your principal to use ‘sts:AssumeRole’, I think.

When you strip out the use of “--profile” you are using your default profile which must have permissions to allow you to run ‘sts:AssumeRole’ on the provided role.

I hope I’m barking up the right tree here - I’m no IAM expert and I have just woken up, but maybe it will give you an idea to go and investigate...

Let me know how you get on!

**Comment by hussfelt** [comment] 2017-12-14 08:14
@hubby What you are saying is true, and this is how we set it up. I can assume all these roles in the AWS console and through the ```aws sts``` command. But not specifying a profile that sources my default credentials.

Note that I can call the command without specifying the profile and assume the role. But not specifying the profile - even though the source_profile points to the default one.

The PR i passed you is valid in this case either way I think. Then this would also work without specifying a source_profile. It should also not affect the expected behaviour of the tool :-)

**Comment by hussfelt** [comment] 2017-12-14 08:18
I posted a bug in AWS CLI, as this is very unclear behaviour. :)
Patch still valid though :)

**Comment by hybby** [comment] 2017-12-14 08:22
Thanks! Could you link to the bug report you have made? I am quite interested.

I’ll have a further look at your PR when I’m at a laptop and merge if all seems good. Something does seem slightly off about the error you’re recieving, though! I’ll try and reproduce.

**Comment by hussfelt** [comment] 2017-12-14 08:28
@hybby it's linked above :)
https://github.com/aws/aws-cli/issues/3039

**Comment by hybby** [comment] 2017-12-14 11:14
Hm, I've had a look and all of my profiles are configured in `~/.aws/config` and source a default profile.  Here's an example:

```
[default]
output = json
region = us-east-1

[profile poweruser]
output = json
region = us-east-1
role_arn = arn:aws:iam::123456789000:role/MyPowerUserProfile
source_profile = default
mfa_serial = arn:aws:iam::123456789000:mfa/drew.jess
```

My `~/.aws/credentials` file is identical to yours.

When I execute this:

```
$ aws sts assume-role --role-arn arn:aws:iam::123456789000:role/MyPowerUserProfile --role-session-name poweruser123 --profile poweruser
```

I get the expected JSON response:

```
{
    "AssumedRoleUser": {
        "AssumedRoleId": "<omitted>:poweruser123",
        "Arn": "arn:aws:iam::123456789000:role/MyPowerUserProfile/poweruser123"
    },
    "Credentials": {
        "SecretAccessKey": "<omitted>",
        "SessionToken": "<omitted>",
        "Expiration": "2017-12-14T11:54:36Z",
        "AccessKeyId": "<omitted>"
    }
}
```

The principal that I'm using (my IAM user) has a group membership which has an attached policy allowing `sts:AssumeRole` to the ARN of `arn:aws:iam::123456789000:role/MyPowerUserProfile`.  If the role you're assuming is cross-account, then the role requires a trust relationship to the source account that you're connecting from.

I read about this [here](http://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html), but I'm sure you know all that already, since it's working for you via the console.

Is there a chance that the role you're trying to assume requires `aws:MultiFactorAuthPresent` in its trust relationship and you haven't got `mfa_serial` specified in your profiles?  

I am able to reproduce a similar error if I remove the `mfa_serial` from my profile:

```
$ aws sts assume-role --role-arn arn:aws:iam::123456789000:role/MyPowerUserProfile --role-session-name poweruser123 --profile poweruser

An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::000987654321:user/hybby is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789000:role/MyPowerUserProfile
```

The only thing I don't understand is that the principal present in your error appears to be a session of the role that you're trying to assume (`123456789:assumed-role/Implementation/botocore-session-1513236525`) rather than your actual IAM principal.

Are you calling this interactively, or trying to run it through another Python script? I note that your error contains a reference to botocore.  If the latter, you might find that using the `assume-role` API directly via [boto](http://boto.cloudhackers.com/en/latest/ref/sts.html) is more helpful.

It seems that the AWS CLI is working as expected at the version I'm running (`aws-cli/1.11.26 Python/2.7.12 Darwin/17.0.0 botocore/1.4.83`), so I'm not sure that I can merge your proposed fix without understanding the issue a bit more.

**Comment by hussfelt** [comment] 2017-12-14 13:03
@hybby hey! I am going to simplify this a bit - removing the python script all together:

This is me runnning assume-role wihtout the profile attached:

```
# sts assume-role --role-arn arn:aws:iam::123456789:role/Implementation --role-session-name sessionname-141217074137
    {
        "AssumedRoleUser": {
            "AssumedRoleId": "AASDasDSADSAD:sessionname-141217074137",
            "Arn": "arn:aws:sts::123456789:assumed-role/Implementation/sessionname-141217074137"
        },
        "Credentials": {
            "SecretAccessKey": "SECRET",
            "SessionToken": "TOKEN",
            "Expiration": "2017-12-14T13:50:26Z",
            "AccessKeyId": "ACCESSKEY"
        }
    }
```

This is me running assume-role with the profile attached
```
# aws sts assume-role --role-arn arn:aws:iam::123456789:role/Implementation --role-session-name sessionname-141217074137 --profile the-profile-with-the-arn

    An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::123456789:assumed-role/Implementation/botocore-session-1513253382 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::123456789:role/Implementation
```

Profile looks like this:

```
[default]
region = eu-west-1
output = json
[preview]
cloudfront = true

[profile the-profile-with-the-arn]
role_arn = arn:aws:iam::123456789:role/Implementation
source_profile = default
region = eu-west-1
```

Config looks like this:

```
[default]
aws_access_key_id = KEY
aws_secret_access_key = SECRET
```

Important part here is that the IAM Default Access Key/Secret resides in account 987654321 and I assume a role in account 123456789.

Cross assume is confirmed with AWS Console and CLI (as above) when I really use my credentials and not the profile.
Note that the profile specifically tells AWS CLI to use source_profile default, but somewhere along those lines when passing "--profile" it adds something else.

For what I have understood it is supposed to be the IAM credentials I have that Assumes the sub-role.

I really believe there is a loophole in ```aws sts assume-role``` here.
But I also believe that the PR is valid as it only gives the option to use your default credentials - you could have a config where your source_profile points somewhere else but in the specific call you really do want to use your own.

**Comment by hussfelt** [comment] 2017-12-14 13:08
@hybby we are not using MFA.

**Comment by hussfelt** [comment] 2018-01-03 06:39
@hybby Answer from the AWS simply states; Passing a profile to aws sts assume-role, will use the role_arn specified when trying to do the assume itself, and not only the credentials attached to that profile.

This means that when picking the role_arn to assume from the config, the option has to exist to not follow the profile when doing the assume, but rather the default credentials.

Makes sense? :)

**Comment by hussfelt** [comment] 2018-01-17 10:00
Hey @hybby :)

No worries, It's your repo! 👍  I did a fork and pointed our dev-teams to that for now.

The whole issue for us is that you are using a profile, trying to assume a role:
https://github.com/hybby/aws-switchrole/blob/master/aws-switchrole.py#L149

As far as I understand it, using the same profile for sourcing the role_arn creates a "moment 22", not using the profile is best practice as I understand the response from AWS.

> It seems like you're trying to use a profile to assume the role 

https://github.com/aws/aws-cli/issues/3039#issuecomment-352928660

Anyway, feel feel to close this - we'll provide updates to you upstream if anything happens  in our end.

**Comment by hybby** [comment] 2018-01-18 10:50
Thanks @hussfelt.  As mentioned, I'll close this issue.

For what it's worth, my interpretation of @joguSD's comment is slightly different:

> then use an aws sts assume-role operation call to assume arn:aws:iam::123456789:role/Implementation again 

I infer that the "use case that doesn't make sense" is the attempt to switch roles to the same role that's already been assumed.  The action of providing a `--profile` configured with a `role_arn` to my script means that role is assumed immediately on the invocation of the `aws` command.  The IAM User or Group Membership of the credential of the source profile is used to assume that role with an `sts:AssumeRole` call ([source](https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html)).

> The source profile must have permission to call `sts:assume-role` against the role, and the role must have a trust relationship with the source profile to allow itself to be assumed. 

The error that you report seems to stem from the fact that you're trying to use the role to assume itself.  Rather, you want the IAM user or group of the credential to be doing the role assumption.

Of course, I can't determine whether this is the case without more familiarity of the environment that you're looking at and the code that you've written.  My gut feeling is that you're using the script to switch roles and are then attempting to perform another role switch to the same role immediately afterwards.  This causes the role to become the principal that attempts the role change, and as the role doesn't have permissions to assume itself, this fails.  This seems to be what the error message that you alluded to above shows:

> An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts:: 123456789:assumed-role/Implementation/botocore-session-1513236525 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam:: 123456789:role/Implementation

I firmly believe that in this case the "User" should be the IAM user of your credential, not the assumed role session.

The key part seems to be that the profile you're providing contains a `role_arn` that is immediately assumed (successfully) and then `sts assume-role` command is attempting to assume the same role, when it is already assumed.

This command: 

```
aws sts assume-role --role-arn arn:aws:iam:: 123456789:role/Implementation --role-session-name dr-account1-141217074137 --profile dr-notwork
```

in words, reads to me as:

_"First, assume the `role_arn` specified in profile `dr-donotwork`, which is `arn:aws:iam:: 123456789:role/Implementation`.  Then, once you've assumed that role, try to make an `sts:AssumeRole` call to assume role `arn:aws:iam:: 123456789:role/Implementation`."_

When you read this sequence of events aloud, it supports my inference of @joguSD's comment.  I've performed a reasonable amount of testing which supports my understanding of the AWS IAM system and I honestly believe that I'm adhering to best practices, so I hope you understand my reasons for closing this issue.  

Finally, I'd like to say that I really do appreciate your comments - it humbles me to know that something I've written is being used by your team and I hope you can continue to gain some use from it.  Wishing you all the best with your future projects.

**Closed by hybby** 2018-01-18 10:50 UTC
